# Generated by Django 6.0.3 on 2026-03-24 15:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DEMSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_index', models.IntegerField(db_index=True, unique=True)),
                ('filename', models.CharField(max_length=200)),
                ('n_particles', models.IntegerField(default=0)),
                ('timestamp', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Snapshot DEM',
                'ordering': ['file_index'],
            },
        ),
        migrations.CreateModel(
            name='PartitionMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('cartesian', 'Cartésien'), ('cylindrical', 'Cylindrique'), ('voronoi', 'Voronoï (K-means)'), ('quantile', 'Quantile (équi-pop)'), ('octree', 'Octree adaptatif'), ('physics', 'Physics-aware')], db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('parameters', models.JSONField(default=dict, help_text='Paramètres du partitionneur (nx, ny, nz, nr, ntheta, n_cells, ...)')),
                ('label', models.CharField(db_index=True, max_length=200, unique=True)),
                ('n_cells', models.IntegerField(default=0)),
                ('n_cells_visited', models.IntegerField(blank=True, default=0)),
                ('population_mean', models.FloatField(blank=True, null=True)),
                ('population_std', models.FloatField(blank=True, null=True)),
                ('population_cv', models.FloatField(blank=True, help_text='Coefficient de variation = std/mean (plus petit = mieux)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Méthode de partitionnement',
                'ordering': ['name', 'n_cells'],
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(db_index=True, help_text='Nom du dossier dans le bucket HF', max_length=300, unique=True)),
                ('nlt', models.IntegerField(help_text="Nombre de paires de snapshots pour l'apprentissage", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Learning Time (NLT)')),
                ('step_size', models.IntegerField(default=1, help_text="Intervalle entre deux snapshots d'une paire", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Pas temporel (step)')),
                ('start_index', models.IntegerField(default=0, help_text='Premier fichier DEM utilisé', verbose_name='Index de départ')),
                ('n_states', models.IntegerField(default=0, verbose_name="Nombre d'états")),
                ('n_timesteps_used', models.IntegerField(default=0, verbose_name='Timesteps effectifs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bucket_path', models.CharField(blank=True, max_length=500)),
                ('raw_config', models.JSONField(blank=True, default=dict)),
                ('raw_stats', models.JSONField(blank=True, default=dict)),
                ('partition_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='markov.partitionmethod')),
            ],
            options={
                'verbose_name': 'Expérience',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RSDResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('dem', 'DEM (réel)'), ('markov', 'Markov (prédit)')], db_index=True, max_length=10)),
                ('species_criterion', models.CharField(default='z_median', help_text='Critère de séparation des espèces', max_length=50)),
                ('n_steps', models.IntegerField(default=200, verbose_name='Pas de simulation')),
                ('rsd_initial', models.FloatField(verbose_name='RSD initial (%)')),
                ('rsd_final', models.FloatField(verbose_name='RSD final (%)')),
                ('mixing_time_50', models.IntegerField(blank=True, null=True, verbose_name='t₅₀ (RSD÷2)')),
                ('mixing_time_90', models.IntegerField(blank=True, null=True, verbose_name='t₉₀ (RSD÷10)')),
                ('entropy_final', models.FloatField(blank=True, null=True, verbose_name='Entropie finale')),
                ('rsd_curve', models.JSONField(blank=True, default=list, help_text='RSD(t) en pourcentage')),
                ('entropy_curve', models.JSONField(blank=True, default=list)),
                ('concentration_final', models.JSONField(blank=True, default=list, help_text='Concentration par cellule au dernier pas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsd_results', to='markov.experiment')),
            ],
            options={
                'verbose_name': 'Résultat RSD',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransitionMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagonal_mean', models.FloatField(help_text='Moyenne de la diagonale de P', verbose_name='P(rester) moyen')),
                ('diagonal_std', models.FloatField(default=0, verbose_name='σ diagonale')),
                ('diagonal_min', models.FloatField(default=0, verbose_name='Min diagonale')),
                ('diagonal_max', models.FloatField(default=0, verbose_name='Max diagonale')),
                ('row_sum_min', models.FloatField(default=0, verbose_name='Min Σ lignes')),
                ('row_sum_max', models.FloatField(default=0, verbose_name='Max Σ lignes')),
                ('row_sum_mean', models.FloatField(default=0, verbose_name='Moy Σ lignes')),
                ('row_sum_std', models.FloatField(default=0, verbose_name='σ Σ lignes')),
                ('col_sum_min', models.FloatField(default=0, verbose_name='Min Σ colonnes')),
                ('col_sum_max', models.FloatField(default=0, verbose_name='Max Σ colonnes')),
                ('col_sum_mean', models.FloatField(default=0, verbose_name='Moy Σ colonnes')),
                ('n_states_visited', models.IntegerField(default=0, verbose_name='États visités')),
                ('n_states_empty', models.IntegerField(default=0, verbose_name='États vides')),
                ('fraction_visited', models.FloatField(default=0, verbose_name='Fraction visitée')),
                ('eigenvalue_2', models.FloatField(blank=True, help_text='2ème plus grande valeur propre (vitesse de mélange)', null=True, verbose_name='|λ₂|')),
                ('spectral_gap', models.FloatField(blank=True, help_text='1 - |λ₂| (plus grand = mélange plus rapide)', null=True, verbose_name='Gap spectral')),
                ('matrix_bucket_path', models.CharField(help_text='Chemin vers transition_matrix.npy dans le bucket', max_length=500)),
                ('experiment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matrix', to='markov.experiment')),
            ],
            options={
                'verbose_name': 'Matrice de transition',
            },
        ),
        migrations.AddIndex(
            model_name='experiment',
            index=models.Index(fields=['nlt'], name='markov_expe_nlt_275fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='experiment',
            index=models.Index(fields=['step_size'], name='markov_expe_step_si_c213ca_idx'),
        ),
        migrations.AddIndex(
            model_name='experiment',
            index=models.Index(fields=['start_index'], name='markov_expe_start_i_1c7138_idx'),
        ),
        migrations.AddIndex(
            model_name='experiment',
            index=models.Index(fields=['n_states'], name='markov_expe_n_state_adc70a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rsdresult',
            unique_together={('experiment', 'source', 'species_criterion')},
        ),
    ]
