# Generated by Django 6.0.3 on 2026-04-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markov', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitionmethod',
            name='name',
            field=models.CharField(choices=[('cartesian', 'Cartésien'), ('cylindrical', 'Cylindrique'), ('voronoi', 'Voronoï (K-means)'), ('quantile', 'Quantile (équi-pop)'), ('octree', 'Octree adaptatif'), ('physics', 'Physics-aware'), ('adaptive', 'Adaptive'), ('multizone', 'Multizone'), ('single', 'Single')], db_index=True, max_length=50),
        ),
    ]
